Feature/sep6 32 create endpoint for movies where the actors played include the played movies in actor
SEP6-VIA/SEP6 pull request #29
Opened 2023-05-18 10:22 UTC by tomondre

Goal of the PR was to fetch only specific information when fetching all movies, so that the loading time does not take too long. There was a workaround created for the naming convention if jpa method

2023-05-18 10:24 UTC, tomondre commented
I am looking at the refactor to create optional fields

2023-05-18 14:13 UTC, tomondre commented
@KhaledHammoun Please check if there are any problems with the merge, cuz I had to manually merge a ton of code

2023-05-18 15:12 UTC, tomondre commented
> I am looking at the refactor to create optional fields

Done

2023-05-19 06:08 UTC, KhaledHammoun requested changes

2023-05-19 06:08 UTC, KhaledHammoun commented on backend/src/main/java/com/sep6/backend/repository/ActorsRepository.java
> +    PersonMoviesProjection getActorById(int id);
It is missing the Optional here

2023-05-19 06:08 UTC, KhaledHammoun commented on backend/src/main/java/com/sep6/backend/repository/ActorsRepositoryImpl.java
> +    public PersonMoviesProjection getActorById(int id) {
Optional missing

2023-05-19 08:11 UTC, KhaledHammoun approved these changes

2023-05-19 08:31 UTC, merged