Feature/sep6 35 create actor page
SEP6-VIA/SEP6 pull request #40
Opened 2023-05-19 13:20 UTC by Tabita-Roxana

2023-05-19 13:29 UTC, GeorgianaIon requested changes

2023-05-19 13:29 UTC, GeorgianaIon commented on backend/src/main/java/com/sep6/backend/controller/ActorsController.java
> +@CrossOrigin(origins = "http://localhost:3000")
Delete this

2023-05-19 13:29 UTC, GeorgianaIon commented on backend/src/main/java/com/sep6/backend/controller/AuthenticationController.java
> +@CrossOrigin(origins = "http://localhost:3000")
And this

2023-05-19 13:29 UTC, GeorgianaIon commented on frontend/package.json
> +    "babel-preset-es2015": "^6.24.1",
Uninstall babel

2023-05-19 13:29 UTC, GeorgianaIon commented on frontend/src/AppRouter.tsx
> +            <Route path="/actor"  element={<PeoplePage/>} />
maybe the path should look different

2023-05-19 13:29 UTC, GeorgianaIon commented on frontend/src/Pages/people.tsx
> +        const people= await actorService.getSpecificActor(3136)
the id is hardcoded, maybe you can take the id from the url query and use that

2023-05-20 07:15 UTC, KhaledHammoun approved these changes

2023-05-22 13:44 UTC, closed without merging